/*
 * Constantes.h
 *
 *  Created on: 26/10/2012
 *      Author: ezequiel
 */

#ifndef CONSTANTES_H_
#define CONSTANTES_H_

// CONSTANTES DE SUPERFICIES

// CONSTANTES DE PAJAROS
#define RADIO_PAJARO_ROJO 0.1f
#define RESTITUCION_PAJARO_ROJO 0.33f

// CONSTANTES DE DISPAROS
#define RADIO_HUEVO_BLANCO 0.05f
#define RADIO_HUEVO_CODORNIZ 0.03f
#define RADIO_HUEVO_POCHE 0.1f
#define RADIO_HUEVO_RELOJ 0.05f

#endif /* CONSTANTES_H_ */
